# Generated by Django 2.1.7 on 2020-06-20 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('cheese', 'Cheese'), ('1topping', '1 Topping'), ('2topping', '2 toppings'), ('3topping', '3 Toppings')], max_length=64)),
                ('small_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('large_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pizza_type', models.ForeignKey(choices=[('classic', 'Classic Pizza'), ('sicilian', 'Sicilian Pizza')], on_delete=django.db.models.deletion.CASCADE, related_name='pizza_type', to='orders.Category')),
            ],
        ),
    ]
