# Generated by Django 2.1.7 on 2020-06-20 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(choices=[('cheese', 'Cheese'), ('1topping', '1 Topping'), ('2topping', '2 toppings'), ('3topping', '3 Toppings'), ('special', 'Special')], max_length=64),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_type',
            field=models.ForeignKey(choices=[('regular', 'Regular Pizza'), ('sicilian', 'Sicilian Pizza')], on_delete=django.db.models.deletion.CASCADE, related_name='pizza_type', to='orders.Category'),
        ),
    ]
