# Generated by Django 2.1.7 on 2020-06-20 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200620_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizza_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_type', to='orders.Category'),
        ),
    ]
