# Generated by Django 2.1.7 on 2020-06-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200620_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(choices=[('cheese', 'Cheese'), ('1 topping', '1 Topping'), ('2 topping', '2 toppings'), ('3 topping', '3 Toppings'), ('special', 'Special')], max_length=64),
        ),
    ]
