# Generated by Django 2.1.7 on 2020-06-20 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200620_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('small_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('large_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='orders.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='pizza_type',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
