# Generated by Django 2.1.7 on 2020-06-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='max_toppings',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
