# Generated by Django 2.1.7 on 2020-06-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_products_max_toppings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('category', models.CharField(max_length=64)),
                ('subcategory', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('topping1', models.CharField(max_length=64, null=True)),
                ('topping2', models.CharField(max_length=64, null=True)),
                ('topping3', models.CharField(max_length=64, null=True)),
                ('topping4', models.CharField(max_length=64, null=True)),
                ('topping5', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
