# Generated by Django 2.1.7 on 2020-06-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='small', max_length=10),
        ),
    ]
