# Generated by Django 3.1.3 on 2020-11-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_reviews_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='star',
            field=models.IntegerField(null=True),
        ),
    ]
